/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.ProductManagement;

import TheBusiness.Business.Business;
import TheBusiness.ProductManagement.Product;
import TheBusiness.ProductManagement.ProductSummary;
import TheBusiness.Supplier.Supplier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author deep2
 */
public class AdjustTargetPriceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdjustTargetPriceJPanel
     */
    JPanel CardSequencePanel;
    Supplier selectedsupplier;
    Product selectedproduct;

    public AdjustTargetPriceJPanel(Product product, JPanel jp) {

        CardSequencePanel = jp;
        this.selectedproduct = product;
        initComponents();
        refreshTable();

    }


    public void refreshTable() {

       
        ProductSummary productsummary = new ProductSummary(selectedproduct);

        productNameTextField.setText(selectedproduct.toString());
        String revenues = String.valueOf(productsummary.getSalesRevenues());
        productRevenueTextField.setText(revenues);
        productFrequencyAboveTargetTextField.setText( String.valueOf(productsummary.getNumberAboveTarget()));
        productFrequencyBelowTargetTextField.setText( String.valueOf(productsummary.getNumberBelowTarget()));
        productPricePerformanceTextField.setText(String.valueOf(productsummary.getProductPricePerformance()));

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        productNameTextField = new javax.swing.JTextField();
        productFrequencyAboveTargetTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        productRevenueTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        productFrequencyBelowTargetTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        productPricePerformanceTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        newTargetPriceTextField = new javax.swing.JTextField();
        updatePriceButton = new javax.swing.JButton();
        suggestPriceButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Product Performance Summary");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 20, 550, -1));

        jLabel3.setText("Product name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, -1));

        productNameTextField.setEditable(false);
        productNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(productNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, -1));

        productFrequencyAboveTargetTextField.setEditable(false);
        jPanel1.add(productFrequencyAboveTargetTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 150, -1));

        jLabel4.setText("Frequency Above Target");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 150, -1));

        productRevenueTextField.setEditable(false);
        productRevenueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productRevenueTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(productRevenueTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, -1));

        jLabel5.setText("Sales Revenues");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, -1));

        productFrequencyBelowTargetTextField.setEditable(false);
        jPanel1.add(productFrequencyBelowTargetTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 150, -1));

        jLabel6.setText("Frequency Below Target");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 150, -1));

        productPricePerformanceTextField.setEditable(false);
        productPricePerformanceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPricePerformanceTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(productPricePerformanceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 150, -1));

        jLabel7.setText("Marign around target");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 110, -1));

        jLabel1.setText("New Target Price");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 150, -1));
        jPanel1.add(newTargetPriceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 150, -1));

        updatePriceButton.setText("Update Price");
        updatePriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePriceButtonActionPerformed(evt);
            }
        });
        jPanel1.add(updatePriceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 150, -1));

        suggestPriceButton.setText("Suggest Price");
        suggestPriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suggestPriceButtonActionPerformed(evt);
            }
        });
        jPanel1.add(suggestPriceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);

    }//GEN-LAST:event_BackActionPerformed

    private void productNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameTextFieldActionPerformed

    private void productRevenueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productRevenueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productRevenueTextFieldActionPerformed

    private void productPricePerformanceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPricePerformanceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productPricePerformanceTextFieldActionPerformed

    private void updatePriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePriceButtonActionPerformed
        // TODO add your handling code here:
        try {
        // 1. Get the new price from the text field
        int newTargetPrice = Integer.parseInt(newTargetPriceTextField.getText());

        // 2. Get current floor and ceiling prices
        int floorPrice = selectedproduct.getFloorPrice();
        int ceilingPrice = selectedproduct.getCeilingPrice();

        // 3. Validate the new price
        if (newTargetPrice >= floorPrice && newTargetPrice <= ceilingPrice) {

            // 4. Call the updateProduct method
            selectedproduct.updateProduct(floorPrice, ceilingPrice, newTargetPrice);
            JOptionPane.showMessageDialog(this, "Target price updated successfully!");

            // 5. Refresh the performance numbers!
            // This is the "Simulation" part (Task 4)
            refreshTable();

        } else {
            // Show error if price is out of range
            JOptionPane.showMessageDialog(this, "New target price must be between the floor (" + floorPrice + ") and ceiling (" + ceilingPrice + ") prices.", "Invalid Price", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        // Show error if the input is not a valid number
        JOptionPane.showMessageDialog(this, "Please enter a valid number for the target price.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_updatePriceButtonActionPerformed

    private void suggestPriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suggestPriceButtonActionPerformed
        // TODO add your handling code here:
        //by deep 11/11
        // --- This is our new "Algorithm Logic" ---

    // 1. Define our adjustment rule (e.g., 10% adjustment)
    final double ADJUSTMENT_PERCENTAGE = 0.10;

    // 2. Get the product's performance summary
    ProductSummary summary = new ProductSummary(selectedproduct);
    int salesAbove = summary.getNumberAboveTarget();
    int salesBelow = summary.getNumberBelowTarget();

    // 3. Get the current prices
    int currentTarget = selectedproduct.getTargetPrice();
    int floorPrice = selectedproduct.getFloorPrice();
    int ceilingPrice = selectedproduct.getCeilingPrice();

    int suggestedPrice = currentTarget; // Start with the current price

    // 4. Apply the algorithm rules
    if (salesBelow > salesAbove) {
        // Product is UNDERPERFORMING. Suggest a LOWER price.
        suggestedPrice = (int) (currentTarget * (1.0 - ADJUSTMENT_PERCENTAGE));

        // Rule: Don't suggest a price below the floor.
        if (suggestedPrice < floorPrice) {
            suggestedPrice = floorPrice;
        }

    } else if (salesAbove > salesBelow) {
        // Product is OVERPERFORMING. Suggest a HIGHER price.
        suggestedPrice = (int) (currentTarget * (1.0 + ADJUSTMENT_PERCENTAGE));

        // Rule: Don't suggest a price above the ceiling.
        if (suggestedPrice > ceilingPrice) {
            suggestedPrice = ceilingPrice;
        }
    }
    // If salesAbove == salesBelow, the price is balanced, so we suggest no change.

    // 5. Set the suggested price in the text field for the user to approve.
    newTargetPriceTextField.setText(String.valueOf(suggestedPrice));

    JOptionPane.showMessageDialog(this, "A new price has been suggested based on performance.");
    }//GEN-LAST:event_suggestPriceButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField newTargetPriceTextField;
    private javax.swing.JTextField productFrequencyAboveTargetTextField;
    private javax.swing.JTextField productFrequencyBelowTargetTextField;
    private javax.swing.JTextField productNameTextField;
    private javax.swing.JTextField productPricePerformanceTextField;
    private javax.swing.JTextField productRevenueTextField;
    private javax.swing.JButton suggestPriceButton;
    private javax.swing.JButton updatePriceButton;
    // End of variables declaration//GEN-END:variables
}
