/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.ProductManagement;

import TheBusiness.Business.Business;
import TheBusiness.ProductManagement.Product;
import TheBusiness.ProductManagement.ProductSummary;
import TheBusiness.Supplier.Supplier;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author deep25 at 11/11/2025
 */
public class FinalPerformanceReportJPanel extends javax.swing.JPanel {
    private JPanel CardSequencePanel;
    private Business business;
    /**
     * Creates new form FinalPerformanceReportJPanel
     */
    public FinalPerformanceReportJPanel(Business b, JPanel clp) {
    initComponents();
    this.business = b;
    this.CardSequencePanel = clp;
    populateReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReportJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        totalRevenueTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        totalMarginTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));

        BackJButton.setText("Back");
        BackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJButtonActionPerformed(evt);
            }
        });

        ReportJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Supplier", "Product", "Original Target Price", "Current Target Price", "Sales Revenue", "Freq. Above Target", "Freq. Below Target"
            }
        ));
        jScrollPane1.setViewportView(ReportJTable);

        jLabel1.setText("Total company revenue");

        totalRevenueTextField.setEditable(false);

        jLabel2.setText("Total Company Profit Margin");

        totalMarginTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BackJButton)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalRevenueTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalMarginTextField))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackJButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalRevenueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalMarginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJButtonActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_BackJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJButton;
    private javax.swing.JTable ReportJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField totalMarginTextField;
    private javax.swing.JTextField totalRevenueTextField;
    // End of variables declaration//GEN-END:variables
    //by deep 12/11
    public void populateReport() {
    // Get the table model to add rows
    DefaultTableModel dtm = (DefaultTableModel) ReportJTable.getModel();
    dtm.setRowCount(0); // Clear existing rows

    // --- ADD THESE VARIABLES ---
    long companyTotalRevenue = 0;
    long companyTotalMargin = 0;
    // -------------------------

    // Get the list of all suppliers
    ArrayList<Supplier> suppliers = business.getSupplierDirectory().getSuplierList();

    // Loop through all suppliers
    for (Supplier supplier : suppliers) {
        // Loop through all products for the current supplier
        for (Product product : supplier.getProductCatalog().getProductList()) {

            // Get the performance summary for the product
            ProductSummary summary = new ProductSummary(product);

            // --- ADD TO OUR TOTALS ---
            companyTotalRevenue += summary.getSalesRevenues();
            companyTotalMargin += summary.getProductPricePerformance();
            // -------------------------

            // Add a new row to the table
            Object[] row = new Object[7];
            row[0] = supplier.getName();
            row[1] = product.toString(); // Uses the toString() method you already have
            row[2] = product.getOriginalTargetPrice();
            row[3] = product.getTargetPrice();
            row[4] = summary.getSalesRevenues();
            row[5] = summary.getNumberAboveTarget();
            row[6] = summary.getNumberBelowTarget();
            dtm.addRow(row);
        }
    }

    // --- SET THE FINAL TOTALS IN THE UI ---
    totalRevenueTextField.setText(String.valueOf(companyTotalRevenue));
    totalMarginTextField.setText(String.valueOf(companyTotalMargin));
    // ------------------------------------
}
}
